spring.application.name=canje-cheques
spring.main.banner-mode=off
logging.level.root=ERROR

# Rutas CLASSPATH (dentro de src/main/resources)
app.data.banco=classpath:data/banco.txt
app.data.sucursal=classpath:data/sucursal.txt
app.data.cliente=classpath:data/cliente.txt
app.data.cheque=classpath:data/cheque.txt

# Salidas (se crean en runtime)
app.output.dir=output
app.output.reporte=reporte_canje.txt
app.output.cheques=cheques_out.txt

# --- Caso Practico 4: No usamos BD, solo TXT (in-memory) ---
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
